chore: bump lib versions
guidesmiths/systemic-azure-metrics pull request #3
Opened 2021-07-13 11:55 UTC by Betisman

Bump the versions of both application insight libs this lib uses.

2021-07-13 12:08 UTC, kevinccbsg requested changes

2021-07-13 12:08 UTC, kevinccbsg commented on package.json
> +    "applicationinsights": "^2.1.3",
Isn't this a breaking change @Betisman ? `1.4.0` -> `2.1.3` 🙄

2021-07-14 08:26 UTC, UlisesGascon commented on package.json
> +    "applicationinsights": "^2.1.3",
I agree with @kevinccbsg, seems like a breaking change :)

2021-07-14 08:28 UTC, UlisesGascon commented
@Betisman @kevinccbsg  do you want me to add the CI for autopublish in NPM in a separate PR?

2021-07-15 09:34 UTC, kevinccbsg approved these changes
After reviewing the breaking change I think it will not affect us. We don't have node < v8 in our projects.
https://github.com/microsoft/ApplicationInsights-node.js/pull/740

2021-07-15 09:37 UTC, merged